### ISSUE TITLE
Future/ longer term test cases

### ISSUE THREAD

**Issue by pgaviganHC** [hc-sc-ocdo-bdpd/table-processing#13]
Additional test cases needed in the long term:

- Different line styles, thickness, colour, background colours, shading, etc.
- Presence of vertical or angled text
- Different layouts, such as headders in different places
- Multipage tables- Presence of vertical or angled text
- Different layouts, such as headders in different places
- Multipage tables

**Comment by BrennanHCSC** [comment]
This project is not continuing for now. Can potentially revisit in the future.
