### ISSUE TITLE
Handle multirow or multicolumn tables

### ISSUE THREAD

**Issue by pgaviganHC** [hc-sc-ocdo-bdpd/table-processing#9]
The table extraction tools do not handle multirow or multicolumn tables. The evaluation metrics also do not address this limitation.

For now, this limitation needs to be documented in the readme. Longer term functionality needs to be added to the tools to handle this use case.

**Comment by BrennanHCSC** [comment]
This project is not continuing for now. Can potentially revisit in the future.
